networks:
  main:
services:
  rabbit_node_1:
    image: 'rabbitmq:3-management'
    entrypoint: /opt/bunny/docker/rabbitmq/entrypoint.sh /usr/local/bin/docker-entrypoint.sh
    command: rabbitmq-server
    environment:
      RABBITMQ_DEFAULT_USER: testuser
      RABBITMQ_DEFAULT_PASS: testpassword
      RABBITMQ_DEFAULT_VHOST: testvhost
      RABBITMQ_ERLANG_COOKIE: bunny-test-secret
      CONFIG_NAME: "${CONFIG_NAME:-rabbitmq.tls.verify_peer}"
    volumes:
      - .:/opt/bunny
    networks:
      - main
    hostname: rabbit_node_1
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    tty: true
  bunny:
    build: docker/bunny
    environment:
      SSL_TEST: "client"
      SSL_CA: "tls/ca.pem"
      SSL_CLIENT_CERT: "tls/client.pem"
      SSL_CLIENT_KEY: "tls/client.key"
      SSL_PEER_NAME: "server.rmq"
      TEST_RABBITMQ_CONNECTION_URI: "amqp://testuser:testpassword@bunny-rabbit_node_1-1:5672/testvhost"
    volumes:
      - .:/opt/bunny
    networks:
      - main
